theme: jekyll-theme-cayman
title: Pumatics
description: Expert tutoring for AP, Honors, and College courses
url: "https://pumatics.com"
baseurl: ""

# Favicon configuration
favicon:
  ico: /assets/images/favicon.ico
  svg: /assets/images/favicon.svg
  apple_touch: /assets/images/apple-touch-icon.png
  manifest: /assets/images/site.webmanifest

# Business information
business:
  name: Pumatics
  tagline: Elevating academic excellence through personalized tutoring
  founded: 2020
  locations:
    - Remote nationwide

# Social media and contact
social:
  email: info@pumatics.com
  phone: (650) 209-0336
  formspree_id: meoaeoyp

# Navigation
navigation:
  - title: Home
    url: /
  - title: Services
    url: /services
  - title: Pricing
    url: /pricing
  - title: About
    url: /about
  - title: Tutors
    url: /tutors
  - title: Contact
    url: /contact

# Build settings
markdown: kramdown
plugins:
  - jekyll-seo-tag

github: [metadata]