theme: jekyll-theme-cayman
title: Pumatics
description: Expert tutoring for AP, Honors, and College courses
url: "https://pumatics.com"
baseurl: ""

# Business information
business:
  name: Pumatics
  tagline: Elevating academic excellence through personalized tutoring
  founded: 2020
  locations:
    - Remote nationwide

# Social media and contact
social:
  email: info@pumatics.com
  phone: (650) 209-0336

# Navigation
navigation:
  - title: Home
    url: /
  - title: Services
    url: /services
  - title: About
    url: /about
  - title: Tutors
    url: /tutors
  - title: Contact
    url: /contact

# Build settings
markdown: kramdown
plugins:
  - jekyll-seo-tag

github: [metadata]